server:
  port: 8888
  tomcat:
    connection-timeout: 20000
# Apple login 시에만 주석 풀기
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: creamelocal-ssl
#    key-store-type: PKCS12
#    key-alias: creamelocal-ssl

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 40MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/creame
#    username: creamelocal
#    password: creame123!@#
    url: jdbc:mysql://192.168.75.132:5748/cream
    username: cream
    password: cream123
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: dbpool-creame
  jpa:
    hibernate:
      ddl-auto: none # validate (?? ? ??) | update | none | create | create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy # ????
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # ????
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true

#  /resource ?? ?? schema.sql, data.sql ? ???? ??? ??
#  sql:
#    init:
#      mode: EMBEDDED
#  h2:
#    console:
#      enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# todo: sms 에 캡슐환 된 상태로 구조 변경
services:
  external:
    sms:
      host: https://api.coolsms.co.kr
      api-key: ENC(flAOE2cNFc3MXk+EXCegfVa55/DE+Go1qqUgv5UB7Jk=)
      secret-key: ENC(6z7KXRNXQNj/8WV/4eoehtkF8EukPbbp9ja7qD0VUVfN6zGioZAegLfB5TRN669d)

cloud:
  aws:
    credentials:
      profile-name: creame-service
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: today.cream.file

aws:
  paramstore:
    enabled: true
    prefix: /creame
    name: web
    profile-separator: .
    fail-fast: true

m2net:
  cpid: "0014"
  authkey: iP8n7GrCOrVic4qJ6dpmTIKg
  host: http://passcall.co.kr:25205

logging:
  config: classpath:logback/logback-local.xml

## 소셜 로그인
google:
  client:
    id: 32549201423-r5caiq9vkt6pmteie0s98c2ln5fbr9aa.apps.googleusercontent.com
    secret: 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
  redirect_uri: http://localhost:8888/public/v1/login/oauth/GOOGLE
  scope: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
  auth_url: https://accounts.google.com/o/oauth2/v2/auth
  token_url: https://oauth2.googleapis.com

naver:
  client:
    id: WpDQLYpuiT3WX9sVxfVp
    secret: GDqVctmMMN
  redirect_uri: http://localhost:8888/public/v1/login/oauth/NAVER
  scope:
  auth_url: https://nid.naver.com/oauth2.0/authorize
  token_url: https://nid.naver.com/oauth2.0
  profile_url: https://openapi.naver.com

apple:
  client:
    team_id: VJ8S7P66WS
    id: com.creame.local.service
    key: 5R9SFB2Z25
#  redirect_uri: http://localhost:8888/public/v1/login/oauth/APPLE
  redirect_uri: https://creamelocal.com:8888/public/v1/login/oauth/APPLE
  key_path: apple/local/AuthKey_5R9SFB2Z25.p8
  base_url: https://appleid.apple.com

kakao:
  client:
    id: f7be4ffc92d35008097763c3c750b3e9
    secret: jGoCWpx0CKYQoyBuVHOapDiGSgXfQ7JI
  redirect_uri: http://localhost:8888/public/v1/login/oauth/KAKAO
  scope: profile_nickname account_email
  token_url: https://kauth.kakao.com
  oauth_url: https://kauth.kakao.com
  profile_url: https://kapi.kakao.com