server:
  port: 8888

spring:

  config:
    import: 'aws-parameterstore:'
    activate:
      on-profile: default
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 40MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdb-creame.c7f9pyzwo76e.ap-northeast-2.rds.amazonaws.com:3306/creame?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: ENC(DFXaDe/wgo4HzmpZ35XZBUFe7ANBMKBL)
    password: ENC(JdZ7/UOKRzJ2xblyENpWYGXy/mzBGBil)
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: dbpool-creame
  jpa:
    hibernate:
      ddl-auto: validate # validate (?? ? ??) | update | none | create | create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy # ????
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # ????
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true

#  /resource ?? ?? schema.sql, data.sql ? ???? ??? ??
#  sql:
#    init:
#      mode: EMBEDDED
#  h2:
#    console:
#      enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

# todo: sms 에 캡슐환 된 상태로 구조 변경
services:
  external:
    sms:
      host: https://api.coolsms.co.kr
      api-key: ENC(flAOE2cNFc3MXk+EXCegfVa55/DE+Go1qqUgv5UB7Jk=)
      secret-key: ENC(6z7KXRNXQNj/8WV/4eoehtkF8EukPbbp9ja7qD0VUVfN6zGioZAegLfB5TRN669d)

cloud:
  aws:
    credentials:
      profile-name: creame.service
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: today.cream.file

aws:
  paramstore:
    enabled: true
    prefix: /creame
    profile-separator: .
    name: web
    fail-fast: true

logging:
  level:
    root: info
    today.creame: debug
    org.springframework: warn
    org.springframework.web: warn
    org.hibernate: debug
    springfox: info
    com.amazonaws.util.EC2MetadataUtils: ERROR


