### access token 재발급 (사용자) - 88

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjc5MjkwMTMwLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0.LaDwSEapSWSQ2SQpQa4vi7tvShSD-FyNkcdzv0dtsTc

### 핫인플루언스 등록

PUT {{host}}/admin/v1/banners/hot
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc2NjQ0NzY3LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.3tXgqq0HM96GItvAMSUb71rTzc5XJycH78F8ku2pbMo

{
  "influence_id": 70,
  "title": "연애 인플루언스",
  "banner_image_uri": "https://s3.ap-northeast-2.amazonaws.com/today.creame.file/temp/20230217/20230217022559-10003.png",
  "order_number": "2"
}

### 인플루언스 신청 조회

GET {{host}}/admin/v1/influence/applications
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjc4NzE4MzM0LCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0.nWmb2Mh_YvA8pYjkNoyBkYzT7p_oV6F8HxRoakZsZfw


### 인플루언스 승인

PATCH {{host}}/admin/v1/influence/applications/56/approve
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjc4NzE4MzM0LCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0.nWmb2Mh_YvA8pYjkNoyBkYzT7p_oV6F8HxRoakZsZfw


### 운영진에 문의하기

POST {{host}}/api/v1/qna
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc3Mzk4Njk4LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.zA2D63v-8kaXzZu8e02u7hpGeQgL2dGeWc_S75e2eeo

{
  "category": "GENERAL",
  "title": "제목",
  "content": "본문",
  "attach_files": [
    {
      "file_id": 1,
      "file_uri": "https://...."
    },
    {
      "file_id": 2,
      "file_uri": "https://...."
    }
  ]
}