### 로그인 (인플루언스) -- 50

POST {{host}}/public/v1/login
Content-Type: application/json

{
  "username": "kkkhjin1234@gmail.com",
  "password" : "QIA@u!px0p"
}

### 로그인 (일반유저) -- 42

POST {{host}}/public/v1/login
Content-Type: application/json

{
  "username": "ethan.bud99@gmail.com",
  "password" : "1234"
}

### access token 재발급 (사용자) - 42

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6ImV0aGFuIiwiaWQiOjQyLCJleHAiOjE2Njk5OTEyNDMsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJldGhhbi5idWQ5OUBnbWFpbC5jb20ifQ.FO_FKKtqcq6cYeNxFrSOvT7Pc5yDzPgjbzsPwzpTMm4

### access token 재발급 (관리자)

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc2OTcyOTEzLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.nOc_FZKgjnE4jNmRFXbr9D_mDgknl0zZVoVhlW1Zp_w

### access token 재발급 (인플루언스)

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc2OTcyOTEzLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.nOc_FZKgjnE4jNmRFXbr9D_mDgknl0zZVoVhlW1Zp_w