### 로그인

POST {{host}}/public/v1/login
Content-Type: application/json

{
  "username": "user0930@gmail.com",
  "password" : "1234"
}

### access token 재발급

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6InRlc3QtdXNlci1uaWNrIiwiaWQiOjI4LCJleHAiOjE2NjY1Mzk3MjgsImF1dGhvcml0aWVzIjoiVVNFUiIsInVzZXJuYW1lIjoidGVzdC11c2VyQGNyZWFtZS5jby5rciJ9.0eUiead5C7Cu4PFho7e2WCV03J1v5lJ5ie2Ri-IzzaM

{

}