### 로그인

POST {{host}}/public/v1/login
Content-Type: application/json

{
  "username": "user0930@gmail.com",
  "password" : "1234"
}

### access token 재발급 (사용자)

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6ImZpcnN0LXVzZXIiLCJpZCI6MjAsImV4cCI6MTY2NzM1NTIxNSwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJ1c2VybmFtZSI6ImZpcnN0LXVzZXJAY3JlYW1lLmNvLmtyIn0.AauZNyDzCNa5CmclB1ye5ZOXYZt4_KB32VzH2h9vWI8

### access token 재발급 (관리자)

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6InVzZXIwOTMwIiwiaWQiOjQwLCJleHAiOjE2NjczNTY5NzAsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSLFJPTEVfQURNSU4iLCJ1c2VybmFtZSI6InVzZXIwOTMwQGdtYWlsLmNvbSJ9.XzRfbUBJVfLuexhUwldUZBnGtwQqqSnr5Xxbb2ZFp0I