### PreSigned URL

POST {{host}}/public/v1/temp-profile-image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files"; filename="img_0.png"

< ../HELP.md

#--boundary
#Content-Disposition: form-data; name="files"; filename="img_1.png"
#
#< ../img_1.png

#--boundary
#Content-Disposition: form-data; name="second"; filename="input-second.txt"
#
#// A temporary 'input-second.txt' file with the 'Text' content will be created and uploaded
#Text
#--boundary
#Content-Disposition: form-data; name="third";
#
#// The 'input.txt' file contents will be sent as plain text.
#< ./input.txt --boundary--


###

GET {{host}}/public/v1/commons/item-code
Content-Type: application/json

