###
GET {{host}}/public/v1/home/top-banner
Content-Type: application/json

###
GET {{host}}/public/v1/home/influence/stat
Content-Type: application/json


### 조회
GET {{host}}/public/v1/home/influences?listType=ALL&page=0&size=20
Content-Type: application/json

{
}


### 검색
GET {{host}}/public/v1/home/influences?type=KEYWORD&keyword=심리
#GET {{host}}/public/v1/home/influences?type=RECOMMEND
Content-Type: application/json