### 50

### 인플루언스 신청

POST {{host}}/public/v1/influence/applications
Content-Type: application/json

{
  "name": "주니",
  "nickname": "Meemee",
  "email": "meemee@lendit.com",
  "phone_number": "01089834350",
  "introduction": "안녕하세요. 잘부탁드립니다.",
  "categories": [
    "DATING",
    "BEAUTY"
  ],
  "profile_image_ids": [
    158,
    159,
    160
  ]
}

### 인플루언스 신청 조회

GET {{host}}/admin/v1/influence/applications
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc3NzM3MDMxLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.F875nslif3mbIopWwJSryUHOoWZ79nyuHiCP_Fqv2SU


### 인플루언스 승인

PATCH {{host}}/admin/v1/influence/applications/31/approve
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc3NzM3MDMxLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.F875nslif3mbIopWwJSryUHOoWZ79nyuHiCP_Fqv2SU


### 인플루언스 조회
GET {{host}}/public/v1/influences/70
Content-Type: application/json

### 북마크 조회

GET {{host}}/api/v1/influences/{{influence_id}}/bookmark
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc3NjcxMDA4LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.Ini-Rt4LMxSzomPjeDXR5kjjQtswuhxRZPHZcXFWem4

{

}

### 북마크 설정

PATCH {{host}}/api/v1/influences/{{influence_id}}/bookmark/mark
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6ImZpcnN0LXVzZXIiLCJpZCI6MjAsImV4cCI6MTY2NzcyNjM5MywiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJ1c2VybmFtZSI6ImZpcnN0LXVzZXJAY3JlYW1lLmNvLmtyIn0.fMjxReo-ktG2yyw3cO9roFvQC17hEMLCfruUOwRKrn8

{

}

### 북마크 취소

PATCH {{host}}/api/v1/influences/{{influence_id}}/bookmark/cancel
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6ImZpcnN0LXVzZXIiLCJpZCI6MjAsImV4cCI6MTY2NzcyNjM5MywiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJ1c2VybmFtZSI6ImZpcnN0LXVzZXJAY3JlYW1lLmNvLmtyIn0.fMjxReo-ktG2yyw3cO9roFvQC17hEMLCfruUOwRKrn8

{

}

### Qna 등록
POST {{host}}/api/v1/influences/{{influence_id}}/qna
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6ImV0aGFuIiwiaWQiOjQyLCJleHAiOjE2NjgxNjMyMjQsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJldGhhbi5idWQ5OUBnbWFpbC5jb20ifQ.hj1bkfYqghwjmYIoBmozhEgpLv1B-r2EH0bQy1vpyjQ

{
  "content": "질문드립니다."
}

### Qna 답변
POST {{host}}/api/v1/influences/{{influence_id}}/qna/10/answer
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjY4MTYzMzIwLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoia2traGppbjEyMzRAZ21haWwuY29tIn0.SabbGm_jkRELTD0TM8jNxJwv4C7a8DI381mv5AoqMy0

{
  "content": "답변완료"
}

### Qna 조회
GET {{host}}/public/v1/influences/{{influence_id}}/qna
Content-Type: application/json

{
}

### 인사말 등록
POST {{host}}/api/v1/influence/50/greetings
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc3NDkyMDE5LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.4zjWqz5zItJr45iZrec_LRT3VNYOXaOjjhFphmLE_xc

{
  "file_id": 166,
  "file_uri": "https://s3.ap-northeast-2.amazonaws.com/today.creame.file/temp/20230219/20230219205438-10004.mp4"
}

### 인사말 조회
GET {{host}}/api/v1/influence/50/greetings/latest
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc3NjcxMDA4LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.Ini-Rt4LMxSzomPjeDXR5kjjQtswuhxRZPHZcXFWem4


### SNS 등록
PUT {{host}}/api/v1/influence/70/sns
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuydtOyLnOuMgOuniOyngOunieyduO2UjOujqOyWuOyKpCIsImlkIjo3MCwiZXhwIjoxNjc3NzkxNDk2LCJhdXRob3JpdGllcyI6IlJPTEVfSU5GTFVFTkNFLFJPTEVfVVNFUiIsInVzZXJuYW1lIjoic2VjMjJAZ21haWwuY29tIn0.CPHEfka-8IrnaTziEDPT0nwtbEYKnzX8jhi8MDaOH9w

{
  "sns_company": "INSTAGRAM",
  "address": "https://instagram.com/hhhhothae"
}

### 인플루언스 공지 등록
PUT {{host}}/api/v1/influence/50/notice
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc3NTc4MzkyLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.yiTNfmMuolQsvE_UMp8MlDwdnR0m26Lnyip-L1oRZQY

{
  "content": "[ test ] 테스트 공지",
  "attach_files": [
    {
      "file_id": 1,
      "file_uri": "https://...."
    },
    {
      "file_id": 2,
      "file_uri": "https://...."
    }
  ]
}