### 인플루언스 신청

POST {{host}}/public/v1/influence/applications
Content-Type: application/json

{
  "name": "갤럭시",
  "nickname": "갠역시",
  "email": "galuxy@daum.net",
  "phone_number": "01036783455",
  "introduction": "안녕하세요. 잘부탁드립니다.",
  "categories": [
    "DATING",
    "BEAUTY"
  ],
  "profile_image_ids": [
    158,
    159,
    160
  ]
}

### 로그인 (관리자) -- 50

POST {{host}}/public/v1/login
Content-Type: application/json

{
  "username": "kkkhjin1234@gmail.com",
  "password": "QIA@u!px0p"
}


### 토큰 재발급

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc4NzU4ODcxLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.bSXPVpIEtMJ199x4UtWMvRa34GBH3QlSHekUQAvoasA


### 인플루언스 신청 조회

GET {{host}}/admin/v1/influence/applications
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc4MTc1ODQ5LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.X8HsglMipzm2u4JJn5KNspYy_alrGc2tmbM5aA8KyoU


### 인플루언스 승인

PATCH {{host}}/admin/v1/influence/applications/approve
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjkxMzA0NTIzLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0.Wtw9x0CbkQtqcYdO0h4ZNeHW-t9-a2qzcZuBs5VMGvk

{
	"ids": [
		1,2,3
	]
}

### 인플루언스 중복 승인

PATCH {{host}}/admin/v1/influence/applications/duplicate/approve
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjkxMzA0NTIzLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0.Wtw9x0CbkQtqcYdO0h4ZNeHW-t9-a2qzcZuBs5VMGvk

{
  "ids": [
    1,2,3
  ]
}

### 인플루언스 거절

PATCH {{host}}/admin/v1/influence/applications/52/reject
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjgwODg4MDcwLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0._e82Lv7D3bxTMTrHiQL_VVAUxCSjnDo1v6XHhFn9Dy4

{
  "ids": [
    1,2,3
  ]
}


### 인플루언스 상세 조회

GET {{host}}/admin/v1/influence/applications/92
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjkxMzA0NTIzLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0.Wtw9x0CbkQtqcYdO0h4ZNeHW-t9-a2qzcZuBs5VMGvk
