### 통화 전 통보

PUT {{host}}/api/v1/m2net/pre-call/70
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6Iuu5teq1rOuYpeq1rCIsImlkIjo0MiwiZXhwIjoxNjc2NzY3MTI2LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiZXRoYW4uYnVkOTlAZ21haWwuY29tIn0.IByis6BmsThnCqW6S0xChHctOwzhnyYy3AlOA8ag9mM

### 통화시작

POST {{host}}/m2net/call-status
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6Iuu5teq1rOuYpeq1rCIsImlkIjo0MiwiZXhwIjoxNjc2NzY3MTI2LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiZXRoYW4uYnVkOTlAZ21haWwuY29tIn0.IByis6BmsThnCqW6S0xChHctOwzhnyYy3AlOA8ag9mM

{
  "callid": "336a98a02f1d361e63616c6c00279d31@211.175.205.120",
  "cpid" : "0014",
  "csrid" : "12805",
  "dtmfno": "103",
  "start": "2023-09-28 22:20:00",
  "end": null,
  "eventtm": "2023-09-27 23:41:27",
  "membid" : "036616",
  "from":"01039960399",
  "to":"07080171700",
  "usetm": 0,
  "amt": 0,
  "telno": "01032114161",
  "reason": "CONNECT_CSR",
  "preflag": "Y"
}

### 통화종료

POST {{host}}/m2net/call-status
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6Iuu5teq1rOuYpeq1rCIsImlkIjo0MiwiZXhwIjoxNjc2NzY3MTI2LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiZXRoYW4uYnVkOTlAZ21haWwuY29tIn0.IByis6BmsThnCqW6S0xChHctOwzhnyYy3AlOA8ag9mM

{
  "callid": "336a98a02f1d361e63616c6c00279d31@211.175.205.120",
  "cpid" : "0014",
  "csrid" : "12805",
  "dtmfno": "103",
  "start": "2023-09-28 22:20:00",
  "end": "2023-09-28 22:25:00",
  "eventtm": "2023-09-27 23:41:27",
  "membid" : "036616",
  "from":"01039960399",
  "to":"07080171700",
  "usetm": 300,
  "amt": 500,
  "telno": "01032114161",
  "reason": "DISCONNECT",
  "preflag": "Y"
}

### 통화내역

GET {{host}}/api/v1/me/matching-history?since=1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuugiOuEiOuTnCIsImlkIjo5MCwiZXhwIjoxNjgzOTg2MjkzLCJhdXRob3JpdGllcyI6IlJPTEVfSU5GTFVFTkNFLFJPTEVfVVNFUiIsInVzZXJuYW1lIjoiaG9wZW1hbjk3QGhhbm1haWwubmV0In0.7_W857twqFOAgXGpcXFS48-ixphLVUojpjydqyFQYx8


### 통화내역 상세보기
GET {{host}}/api/v1/me/matching-history/7
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuugiOuEiOuTnCIsImlkIjo5MCwiZXhwIjoxNjgzOTg2MjkzLCJhdXRob3JpdGllcyI6IlJPTEVfSU5GTFVFTkNFLFJPTEVfVVNFUiIsInVzZXJuYW1lIjoiaG9wZW1hbjk3QGhhbm1haWwubmV0In0.7_W857twqFOAgXGpcXFS48-ixphLVUojpjydqyFQYx8

### 나의 후기

GET {{host}}/api/v1/me/reviews
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuugiOuEiOuTnCIsImlkIjo5MCwiZXhwIjoxNjgzOTg2MjkzLCJhdXRob3JpdGllcyI6IlJPTEVfSU5GTFVFTkNFLFJPTEVfVVNFUiIsInVzZXJuYW1lIjoiaG9wZW1hbjk3QGhhbm1haWwubmV0In0.7_W857twqFOAgXGpcXFS48-ixphLVUojpjydqyFQYx8

### 후기 등록

POST {{host}}/api/v1/matchings/8/reviews
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuugiOuEiOuTnCIsImlkIjo5MCwiZXhwIjoxNjgzOTg2MjkzLCJhdXRob3JpdGllcyI6IlJPTEVfSU5GTFVFTkNFLFJPTEVfVVNFUiIsInVzZXJuYW1lIjoiaG9wZW1hbjk3QGhhbm1haWwubmV0In0.7_W857twqFOAgXGpcXFS48-ixphLVUojpjydqyFQYx8

{
  "rate": 5,
  "category": "BABY",
  "review_kinds": "KINDNESS",
  "content": "와우! 내 생애 최고의 통화였어요."
}

### 인플루언스 후기 목록

GET {{host}}/public/v1/influences/90/reviews?direction=ASC
Content-Type: application/json

### 월별 내역

GET {{host}}/api/v1/matchings/stat?from=202306&to=202309
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6Iu2YnOyEnOuLiF8iLCJpZCI6MTQ4LCJleHAiOjE2OTQ4NjIyNDMsImF1dGhvcml0aWVzIjoiUk9MRV9JTkZMVUVOQ0UsUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJwX2J5X21lN0BuYXZlci5jb20ifQ.9f7IZhUxws7IY0ehiYs_UaMIENgzMbcLRhEwGQ0s-Uw

### 월별 상세 내역

GET {{host}}/api/v1/matchings/stat/selected?date=202309
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6Iu2YnOyEnOuLiF8iLCJpZCI6MTQ4LCJleHAiOjE2OTQ4NjIyNDMsImF1dGhvcml0aWVzIjoiUk9MRV9JTkZMVUVOQ0UsUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJwX2J5X21lN0BuYXZlci5jb20ifQ.9f7IZhUxws7IY0ehiYs_UaMIENgzMbcLRhEwGQ0s-Uw

### 인플루언스 문의 목록

GET {{host}}/public/v1/influences/90/questions?page=0&size=20
Content-Type: application/json

### 월별 내역

GET {{host}}/api/v1/matchings/stat?to=202307&from=202305
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuylrOylrCIsImlkIjoxMDMsImV4cCI6MTY4OTQyNDIxMywiYXV0aG9yaXRpZXMiOiJST0xFX0lORkxVRU5DRSxST0xFX1VTRVIiLCJ1c2VybmFtZSI6Imh5ZXJpbjEwMDZAbmF2ZXIuY29tIn0.dNhSAMSG4sKC1xLu4viL6LOrO9LEBIJz5b1VY3xABYU

### 인플루언스 문의 목록

GET {{host}}/public/v1/influences/90/questions
Content-Type: application/json

### 통화시간
GET {{host}}/admin/v1/matching/MEMBER
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyWtOuTnOuvvCIsImlkIjo4OCwiZXhwIjoxNjkzNjY5MzA0LCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImppbmtoOTdAZ21haWwuY29tIn0.3gE66G0_jGTDd5ODNUAd5l38Do5-W4djqaBCGzF-uww


