### 회원가입
### phone_verification 테이블에 임의 값 등록 후 진행
POST http://localhost:8888/public/v1/members
Content-Type: application/json

{
  "email": "keehwan@naver.com",
  "password": "1234",
  "nickname": "HellWorld",
  "phone_number": "01043993399",
  "phone_verified_code": "7529383668"
}

### 로그인 후 정보

GET {{host}}/api/v1/me
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc4MDAwOTI4LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.msqYZg7iPcwfx9VqITZywWFq_n-9y2E2FiuvI6jPGzc

### 이메일 찾기

POST {{host}}/public/v1/forget-email
Content-Type: application/json

{
  "token": 7949017884,
  "phone_number": "01039960399"
}

### 패스워드 찾기

POST {{host}}/public/v1/forget-password
Content-Type: application/json

{
  "email": "keeyoung@naver.com",
  "token": 7949017884,
  "phone_number": "01039960399"
}

### 닉네임 변경

PATCH {{host}}/api/v1/members/42/nickname
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6ImV0aGFuIiwiaWQiOjQyLCJleHAiOjE2NjkzODc2NDMsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJldGhhbi5idWQ5OUBnbWFpbC5jb20ifQ.-f1kp3O-hPNcHGw5IDVDGCxR8e-EKZ3JYEPQUR9FdSo

{
  "nickname": "빵구똥구"
}


### 알림 설정 조회

GET {{host}}/api/v1/me/notifications
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuyZlOuKlOqwgCIsImlkIjo1MCwiZXhwIjoxNjc4MDAwOTI4LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUixST0xFX0FETUlOIiwidXNlcm5hbWUiOiJra2toamluMTIzNEBnbWFpbC5jb20ifQ.msqYZg7iPcwfx9VqITZywWFq_n-9y2E2FiuvI6jPGzc

{
}


### 알림 설정 변경

PATCH {{host}}/api/v1/members/42/notifications/SMS/ON
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6ImV0aGFuIiwiaWQiOjQyLCJleHAiOjE2NjkzODc2NDMsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwidXNlcm5hbWUiOiJldGhhbi5idWQ5OUBnbWFpbC5jb20ifQ.-f1kp3O-hPNcHGw5IDVDGCxR8e-EKZ3JYEPQUR9FdSo

{
}


### 단골 (즐겨찾기 상담사)
GET {{host}}/api/v1/influences-bookmark
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6Iuu5teq1rOuYpeq1rCIsImlkIjo0MiwiZXhwIjoxNjc3Njc1OTU2LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiZXRoYW4uYnVkOTlAZ21haWwuY29tIn0.HIdgbMvnRR7Z6gXPhTAM_jTD5_xyZYtgA2-EGuZPCNA

### 단골 (최근 통화)
GET {{host}}/api/v1/influences-recently
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6Iuu5teq1rOuYpeq1rCIsImlkIjo0MiwiZXhwIjoxNjc3NTcwMDczLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiZXRoYW4uYnVkOTlAZ21haWwuY29tIn0.1nbVZKKLkCXn_H_fuRv8SzzUquTRQKNbeQX7y16CsFg
