### 회원가입

POST http://localhost:8888/public/v1/members
Content-Type: application/json

{
  "email": "1041@gmail.com",
  "password": "1234",
  "nickname": "user11111",
  "phone_number": "01009270930",
  "phone_verified_code": "1234"
}

### 로그인

POST {{host}}/public/v1/login
Content-Type: application/json

{
  "username": "test-user@creame.co.kr",
  "password" : "1234"
}
