### 회원가입

POST http://localhost:8888/public/v1/members
Content-Type: application/json

{
  "email": "test-user@creame.co.kr",
  "password": "1234",
  "nickname": "test-user-nick",
  "phone_number": "01033339999"
}

### 로그인

POST http://localhost:8888/public/v1/login
Content-Type: application/json

{
  "username": "test-user@creame.co.kr",
  "password" : "1234"
}