### access token 재발급 (사용자) - 42

POST {{host}}/public/v1/token/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuuniOyKpO2EsOycoOyggCIsImlkIjo4MCwiZXhwIjoxNjc5MDY5NTAzLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiaG9wZW1hbjk3QGhhbm1haWwubmV0In0.Nlt_sB_On-9KstuORQ3E9FWMH8RoDL61SkQjszWgp8M


### 카드등록

POST {{host}}/api/v1/me/payments/bill-key
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuuniOyKpO2EsOycoOyggCIsImlkIjo4MCwiZXhwIjoxNjc4NjEzODEzLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiaG9wZW1hbjk3QGhhbm1haWwubmV0In0.tRgxBcn67vapr5EAQ73MopIQ-IQ-ZjHkRZn0TQxHqRM

{
  "personal": true,
  "serial": "791231",
  "cardno": "1234567890123456",
  "month": "12",
  "year": "25",
  "card_password": "11",
  "payment_password": "123456"
}

### 카드 조회

GET {{host}}/api/v1/me/payments/credit-card
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDUkVBTUUiLCJuaWNrbmFtZSI6IuuniOyKpO2EsOycoOyggCIsImlkIjo4MCwiZXhwIjoxNjc4NTQwMTI1LCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiaG9wZW1hbjk3QGhhbm1haWwubmV0In0.5f0VcJSczgpTe0A7zXdsgL6pFtHVcK-E_P22E5av8tY
